// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aolaccdyuydnrqnzbmaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvbGFjY2R5dXlkbnJxbnpibWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzA0MjgsImV4cCI6MjA2NTg0NjQyOH0.8A5LEqbTVhNgtKWIcBtYkRxFk0gzuHl1gbjdbnKJ2nQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);